server:
  port: 8080
spring:
  datasource:
    username: root
    password: zjtzjy137381
    url: jdbc:mysql://localhost:3306/upms?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mappers/*.xml

